version: '2'
services:
  couchbase:
    image: realitygames/couchbase-test:latest
    ports:
      - "8091-8094:8091-8094"
      - "11210:11210"
    network_mode: host
    environment:
      - BUCKETS=users viewQuery
      - MEMORY_QUOTA=500
      - TIMEOUT=10
    volumes:
      - ./couchbase/views:/opt/couchbase-views/:ro
      - ./couchbase/data:/opt/couchbase-data/:ro
      - ./couchbase/n1ql:/opt/couchbase-n1ql/:ro
